@WebServer_HostAddress = http://localhost:5001

### Categories

GET {{WebServer_HostAddress}}/api/categories
Accept: application/json

###

GET {{WebServer_HostAddress}}/api/categories/1
Accept: application/json

###


DELETE {{WebServer_HostAddress}}/api/categories/9
Accept: application/json

###

POST {{WebServer_HostAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
  "name":"test",
  "description": "blah blah"
}

###

PUT {{WebServer_HostAddress}}/api/categories/1
Accept: application/json
Content-Type: application/json

{
  "name":"Updated Name",
  "description": "Updated Description"
}

###

### Products

GET {{WebServer_HostAddress}}/api/products
Accept: application/json

###